services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  
  app:
    build: .
    ports:
      - "3008:3000" # Map host 3008 to container 3000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: test
    depends_on:
      - db
